var ECLDATA = {};

ECLDATA.mailTargets = {targets: [
	{name: 'Admin ADBANG', emailAddress: 'adbang@bangkalankab.go.id'},
	{name: 'Admin ADPUM', emailAddress: 'adpum@bangkalankab.go.id'},
	{name: 'Admin AROSBAYA', emailAddress: 'arosbaya@bangkalankab.go.id'},
	{name: 'Admin BAKESBANGPOL', emailAddress: 'bakesbangpol@bangkalankab.go.id'},
	{name: 'Admin Bangkalan', emailAddress: 'bangkalan@bangkalankab.go.id'},
	{name: 'Admin BANKPASAR', emailAddress: 'bankpasar@bangkalankab.go.id'},
	{name: 'Admin BAPEMASPEMDES', emailAddress: 'bapemaspemdes@bangkalankab.go.id'},
	{name: 'Admin BAPPEDA', emailAddress: 'bappeda@bangkalankab.go.id'},
	{name: 'Admin BBPKB', emailAddress: 'bbpkb@bangkalankab.go.id'},
	{name: 'Admin BKD', emailAddress: 'bkd@bangkalankab.go.id'},
	{name: 'Admin BKP3', emailAddress: 'bkp3@bangkalankab.go.id'},
	{name: 'Admin Blega', emailAddress: 'blega@bangkalankab.go.id'},
	{name: 'Admin BLH', emailAddress: 'blh@bangkalankab.go.id'},
	{name: 'Admin BPBD', emailAddress: 'bpbd@bangkalankab.go.id'},
	{name: 'Admin BPKAD', emailAddress: 'bpkad@bangkalankab.go.id'},
	{name: 'Admin Burneh', emailAddress: 'burneh@bangkalankab.go.id'},
	{name: 'Admin DINKES', emailAddress: 'dinkes@bangkalankab.go.id'},
	{name: 'Admin DINSOSNAKERTRANS', emailAddress: 'dinsosnakertrans@bangkalankab.go.id'},
	{name: 'Admin DISDIK', emailAddress: 'disdik@bangkalankab.go.id'},
	{name: 'Admin DISHUBKOMINFO', emailAddress: 'dishubkominfo@bangkalankab.go.id'},
	{name: 'Admin DISHUTBUN', emailAddress: 'dishutbun@bangkalankab.go.id'},
	{name: 'Admin DISKOPUMKM', emailAddress: 'diskopumkm@bangkalankab.go.id'},
	{name: 'Admin DISPENDA', emailAddress: 'dispenda@bangkalankab.go.id'},
	{name: 'Admin DISPENDUKCAPIL', emailAddress: 'dispendukcapil@bangkalankab.go.id'},
	{name: 'Admin DISPERINDAG', emailAddress: 'disperindag@bangkalankab.go.id'},
	{name: 'Admin DISPERTAMBEN', emailAddress: 'dispertamben@bangkalankab.go.id'},
	{name: 'Admin DISPERTANAK', emailAddress: 'dispertanak@bangkalankab.go.id'},
	{name: 'Admin DISPORABUDPAR', emailAddress: 'disporabudpar@bangkalankab.go.id'},
	{name: 'Admin DKP', emailAddress: 'dkp@bangkalankab.go.id'},
	{name: 'Admin Galis', emailAddress: 'galis@bangkalankab.go.id'},
	{name: 'Admin Geger', emailAddress: 'geger@bangkalankab.go.id'},
	{name: 'Admin HUKUM', emailAddress: 'hukum@bangkalankab.go.id'},
	{name: 'Admin HUMAS', emailAddress: 'humas@bangkalankab.go.id'},
	{name: 'Admin INSPEKTORAT', emailAddress: 'inspektorat@bangkalankab.go.id'},
	{name: 'Admin Kamal', emailAddress: 'kamal@bangkalankab.go.id'},
	{name: 'Admin Kerjasama', emailAddress: 'kerjasama@bangkalankab.go.id'},
	{name: 'Admin KESRA', emailAddress: 'kesra@bangkalankab.go.id'},
	{name: 'Admin Klampis', emailAddress: 'klampis@bangkalankab.go.id'},
	{name: 'Admin Kokop', emailAddress: 'kokop@bangkalankab.go.id'},
	{name: 'Admin Konang', emailAddress: 'konang@bangkalankab.go.id'},
	{name: 'Admin KORPRI', emailAddress: 'korpri@bangkalankab.go.id'},
	{name: 'Admin KPPT', emailAddress: 'kppt@bangkalankab.go.id'},
	{name: 'Admin Kwanyar', emailAddress: 'kwanyar@bangkalankab.go.id'},
	{name: 'Admin Labang', emailAddress: 'labang@bangkalankab.go.id'},
	{name: 'Admin Modung', emailAddress: 'modung@bangkalankab.go.id'},
	{name: 'Admin NOC Bangkalan', emailAddress: 'admin@bangkalankab.go.id'},
	{name: 'Admin ORGANISASI', emailAddress: 'organisasi@bangkalankab.go.id'},
	{name: 'Admin PASAR', emailAddress: 'pasar@bangkalankab.go.id'},
	{name: 'Admin PDAM', emailAddress: 'pdam@bangkalankab.go.id'},
	{name: 'Admin PEREKONOMIAN', emailAddress: 'perekonomian@bangkalankab.go.id'},
	{name: 'Admin PERLENGKAPAN', emailAddress: 'perlengkapan@bangkalankab.go.id'},
	{name: 'Admin PERPUSTAKAAN', emailAddress: 'perpustakaan@bangkalankab.go.id'},
	{name: 'Admin PUBINAMARGA', emailAddress: 'pubinamarga@bangkalankab.go.id'},
	{name: 'Admin PUCIPTAKARYA', emailAddress: 'puciptakarya@bangkalankab.go.id'},
	{name: 'Admin RSUDSYAMRABU', emailAddress: 'rsudsyamrabu@bangkalankab.go.id'},
	{name: 'Admin Sanditel', emailAddress: 'sanditel@bangkalankab.go.id'},
	{name: 'Admin SATPOLPP', emailAddress: 'satpolpp@bangkalankab.go.id'},
	{name: 'Admin SEKDA', emailAddress: 'sekda@bangkalankab.go.id'},
	{name: 'Admin SEKRETARIATDPRD', emailAddress: 'sekretariatdprd@bangkalankab.go.id'},
	{name: 'Admin Sepulu', emailAddress: 'sepulu@bangkalankab.go.id'},
	{name: 'Admin Setda', emailAddress: 'setda@bangkalankab.go.id'},
	{name: 'Admin Socah', emailAddress: 'socah@bangkalankab.go.id'},
	{name: 'Admin STATISTIK', emailAddress: 'statistik@bangkalankab.go.id'},
	{name: 'Admin SUMBERDAYA', emailAddress: 'sumberdaya@bangkalankab.go.id'},
	{name: 'Admin Tana Merah', emailAddress: 'tanamerah@bangkalankab.go.id'},
	{name: 'Admin Tanjung Bumi', emailAddress: 'tanjungbumi@bangkalankab.go.id'},
	{name: 'Admin Tragah', emailAddress: 'tragah@bangkalankab.go.id'},
	{name: 'Admin UMUM', emailAddress: 'umum@bangkalankab.go.id'},
	{name: 'Kabid Kominfo', emailAddress: 'agus@bangkalankab.go.id'},
	{name: 'Sister JKDN', emailAddress: 'jkdn@bangkalankab.go.id'},
	{name: 'Taufiqurrahman DISHUBKOMINFO', emailAddress: 'tufiq@bangkalankab.go.id'},
]};
